### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by NoriteSC** [izofar/bygone-nether#16]
so what i heard from player's
someone was exploring the nether
and server just crasherd
from server log (i can't include full server log is too large)
[Thread dumps.log](https://github.com/izofar/bygone-nether/files/10438741/Thread.dumps.log)
extracted from Thread dumps
at TRANSFORMER/bygonenether@1.2.1/com.izofar.bygonenether.entity.WarpedEnderMan.randomVariant(WarpedEnderMan.java:167)
at TRANSFORMER/bygonenether@1.2.1/com.izofar.bygonenether.entity.WarpedEnderMan.<init>(WarpedEnderMan.java:58)
at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:469)
at TRANSFORMER/bygonenether@1.2.1/com.izofar.bygonenether.world.feature.MobFeature.m_142674_(MobFeature.java:32)
crash log:
[crash-2023-01-17_18.50.24-server.txt](https://github.com/izofar/bygone-nether/files/10438776/crash-2023-01-17_18.50.24-server.txt)
it occurred using mod pack: https://www.curseforge.com/minecraft/modpacks/better-mc-new (1.19.2 v11)

**Comment by izofar** [comment]
This is an issue due to 1.19's change in `RandomSource`. This is fixed in [5367618](https://github.com/izofar/bygone-nether/commit/536761845c772207070aa7c80400274d4766b658), yet to be released
