### ISSUE TITLE
Server crashes due to bug in porting lib

### ISSUE THREAD

**Issue by Aghast365** [izofar/bygone-nether#27]
With only the fabric version of this mod and fabric API installed, our server would experience sudden, occasional crashes. 

Testing in a creative world found that a baby mob dying to a non-player cause will result in a crash, giving the error message

> java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.ThreadLocal.get()" is null
	at net.minecraft.class_1309.handler$zcg000$porting_lib_base$port_lib$spawnDropsTAIL(class_1309.java:4201)

it seems like this error was the result of a bug in an old version of porting lib, which has since been fixed:
https://github.com/Fabricators-of-Create/Porting-Lib/issues/29

<details>

<summary>edit: crash report</summary>

<pre>
---- Minecraft Crash Report ----
// My bad.

Time: 2023-06-06 23:50:44
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.ThreadLocal.get()" is null
     at net.minecraft.class_1309.handler$zcg000$porting_lib_base$port_lib$spawnDropsTAIL(class_1309.java:4201)
     at net.minecraft.class_1309.method_16080(class_1309.java:1397)
     at net.minecraft.class_1309.method_6078(class_1309.java:1348)
     at net.minecraft.class_1309.method_5643(class_1309.java:1204)
     at net.minecraft.class_1429.method_5643(class_1429.java:80)
     at net.minecraft.class_5137.method_26950(class_5137.java:23)
     at net.minecraft.class_5136.method_6121(class_5136.java:189)
     at net.minecraft.class_4816.method_24590(class_4816.java:50)
     at net.minecraft.class_4816.method_18920(class_4816.java:17)
     at net.minecraft.class_4820.method_18920(class_4820.java:69)
     at net.minecraft.class_4097.method_18922(class_4097.java:49)
     at net.minecraft.class_4095.method_18891(class_4095.java:516)
     at net.minecraft.class_4095.method_19542(class_4095.java:475)
     at net.minecraft.class_5136.method_5958(class_5136.java:255)
     at net.minecraft.class_1308.method_6023(class_1308.java:770)
     at net.minecraft.class_1309.method_6007(class_1309.java:2641)
     at net.minecraft.class_1308.method_6007(class_1308.java:553)
     at net.minecraft.class_1588.method_6007(class_1588.java:44)
     at net.minecraft.class_5136.method_6007(class_5136.java:280)
     at net.minecraft.class_1309.method_5773(class_1309.java:2385)
     at net.minecraft.class_1308.method_5773(class_1308.java:353)
     at net.minecraft.class_3218.method_18762(class_3218.java:712)
     at net.minecraft.class_1937.method_18472(class_1937.java:466)
     at net.minecraft.class_3218.method_31420(class_3218.java:371)
     at net.minecraft.class_5574.method_31791(class_5574.java:54)
     at net.minecraft.class_3218.method_18765(class_3218.java:339)
     at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
     at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
     at net.minecraft.class_1132.method_3748(class_1132.java:98)
     at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
     at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
     at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
     at net.minecraft.class_1309.handler$zcg000$porting_lib_base$port_lib$spawnDropsTAIL(class_1309.java:4201)
     at net.minecraft.class_1309.method_16080(class_1309.java:1397)
     at net.minecraft.class_1309.method_6078(class_1309.java:1348)
     at net.minecraft.class_1309.method_5643(class_1309.java:1204)
     at net.minecraft.class_1429.method_5643(class_1429.java:80)
     at net.minecraft.class_5137.method_26950(class_5137.java:23)
     at net.minecraft.class_5136.method_6121(class_5136.java:189)
     at net.minecraft.class_4816.method_24590(class_4816.java:50)
     at net.minecraft.class_4816.method_18920(class_4816.java:17)
     at net.minecraft.class_4820.method_18920(class_4820.java:69)
     at net.minecraft.class_4097.method_18922(class_4097.java:49)
     at net.minecraft.class_4095.method_18891(class_4095.java:516)
     at net.minecraft.class_4095.method_19542(class_4095.java:475)
     at net.minecraft.class_5136.method_5958(class_5136.java:255)
     at net.minecraft.class_1308.method_6023(class_1308.java:770)
     at net.minecraft.class_1309.method_6007(class_1309.java:2641)
     at net.minecraft.class_1308.method_6007(class_1308.java:553)
     at net.minecraft.class_1588.method_6007(class_1588.java:44)
     at net.minecraft.class_5136.method_6007(class_5136.java:280)
     at net.minecraft.class_1309.method_5773(class_1309.java:2385)
     at net.minecraft.class_1308.method_5773(class_1308.java:353)
     at net.minecraft.class_3218.method_18762(class_3218.java:712)
     at net.minecraft.class_1937.method_18472(class_1937.java:466)
     at net.minecraft.class_3218.method_31420(class_3218.java:371)
     at net.minecraft.class_5574.method_31791(class_5574.java:54)
     at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
     Entity Type: minecraft:zoglin (net.minecraft.class_5136)
     Entity ID: 192
     Entity Name: Zoglin
     Entity's Exact location: 9.23, -60.00, -7.82
     Entity's Block location: World: (9,-60,-8), Section: (at 9,4,8 in 0,-4,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
     Entity's Momentum: -0.08, -0.08, -0.07
     Entity's Passengers: []
     Entity's Vehicle: null
Stacktrace:
     at net.minecraft.class_1937.method_18472(class_1937.java:466)
     at net.minecraft.class_3218.method_31420(class_3218.java:371)
     at net.minecraft.class_5574.method_31791(class_5574.java:54)
     at net.minecraft.class_3218.method_18765(class_3218.java:339)
     at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
     at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
     at net.minecraft.class_1132.method_3748(class_1132.java:98)
     at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
     at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
     at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
     All players: 1 total;
     Chunk stats: 2401
     Level dimension: minecraft:overworld
     Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
     Level time: 829 game time, 829 day time
     Level name: New World
     Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
     Level weather: Rain time: 56013 (now: false), thunder time: 28852 (now: false)
     Known server brands: fabric
     Level was modded: true
     Level storage version: 0x04ABD - Anvil
Stacktrace:
     at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
     at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
     at net.minecraft.class_1132.method_3748(class_1132.java:98)
     at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
     at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
     at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
     Minecraft Version: 1.19.2
     Minecraft Version ID: 1.19.2
     Operating System: Windows 10 (amd64) version 10.0
     Java Version: 17.0.3, Microsoft
     Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
     Fabric Mods: 
          bygonenether: Bygone Nether 1.2.2
               midnightlib: MidnightLib 1.0.0
               porting_lib: Porting Lib 2.1.706+1.19.2
                    forge_tags: Porting Lib Tags 3.0
                    porting_lib_base: Porting Lib Base 2.1.706+1.19.2
                         com_github_llamalad7_mixinextras: MixinExtras 0.1.1
                         mm: Manningham Mills 2.3
                         porting_lib_entity: Porting Lib Entity 2.1.706+1.19.2
                         porting_lib_fake_players: Porting Lib Fake Players 2.1.706+1.19.2
                         serialization_hooks: Serialization Hooks 0.3.26
                    porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.706+1.19.2
                    porting_lib_model_generators: Porting Lib Model Generators 2.1.706+1.19.2
                         porting_lib_models: Porting Lib Models 2.1.706+1.19.2
                              porting_lib_obj_loader: Porting Lib Obj Loader 2.1.706+1.19.2
                                   porting_lib_model_loader: Porting Lib Model Loader 2.1.706+1.19.2
                              porting_lib_transfer: Porting Lib Transfer 2.1.706+1.19.2
                                   porting_lib_extensions: Porting Lib Extensions 2.1.706+1.19.2
                                        porting_lib_accessors: Porting Lib Accessors 2.1.706+1.19.2
                                        porting_lib_attributes: Porting Lib Attributes 2.1.706+1.19.2
                                             porting_lib_constants: Porting Lib Constants 2.1.706+1.19.2
                                        porting_lib_common: Porting Lib Common 2.1.706+1.19.2
                    porting_lib_networking: Porting Lib Networking 2.1.706+1.19.2
          fabric-api: Fabric API 0.76.0+1.19.2
               fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
               fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
               fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
               fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
               fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
               fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
               fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
               fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
               fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
               fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
               fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
               fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
               fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
               fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
               fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
               fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
               fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
               fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
               fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
               fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
               fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
               fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
               fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
               fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
               fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
               fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
               fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
               fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
               fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
               fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
               fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
          fabricloader: Fabric Loader 0.14.21
          java: OpenJDK 64-Bit Server VM 17
          minecraft: Minecraft 1.19.2
     Server Running: true
     Player Count: 1 / 8;
     Data Packs: vanilla, Fabric Mods
     World Generation: Experimental
     Type: Integrated Server (map_client.txt)
     Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
     Launched Version: 1.19.2
</pre>

</details>

**Comment by izofar** [comment]
Fixed in [eb5881b](https://github.com/izofar/bygone-nether/commit/eb5881bc8fd9d6573a8b8e52827f15bdb2e70922)
